package com.example.eHospital;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/cure") // This means URL's start with /demo (after Application path)
public class CureController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CureRepository cureRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewCure (@RequestParam String patient , @RequestParam String doctor , @RequestParam String cure , @RequestParam String drug ,
                                            @RequestParam String result) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Cure n = new Cure();
        n.setPatient(patient);
        n.setDoctor(doctor);
        n.setCure(cure);
        n.setDrug(drug);
        n.setResult(result);
        cureRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Cure> getAllCures() {
        // This returns a JSON or XML with the users
        return cureRepository.findAll();
    }
}
